"""Built-in fallback config for C2 laptops without PyYAML installed."""

from __future__ import annotations

DEFAULT_CONFIG = {
    "arena": {
        "geofence_enabled": True,
        "safety_margin_m": 0.5,
        "uwb_bounds": {"n_min": 0.0, "n_max": 10.0, "e_min": 0.0, "e_max": 5.0},
    },
    "mapping_drone": {
        "aruco_dictionary": "DICT_7X7_1000",
        "valid_marker_ids": [11, 45, 51, 67, 101],
    },
    "navigation": {
        "kp_xy": 0.1,
        "kp_z": 0.1,
        "max_vel_xy": 0.3,
        "max_vel_z": 0.3,
        "max_hover_xy": 0.15,
        "max_hover_z": 0.10,
        "n_threshold": 0.1,
        "e_threshold": 0.1,
        "d_threshold": 0.1,
        "hover_deadband": 0.03,
    },
    "swarm": {
        "listen_seconds": 5,
        "plane_ids": [1, 2, 3],
        "selected_landing_marker_ids": [11, 45, 51],
        "tag_ids": [0, 1, 2],
        "uwb_serial_port": None,
        "uwb_baud_rate": 921600,
        "uwb_origin_x": 5.0,
        "uwb_origin_y": 0.0,
        "uwb_nav_timeout_s": None,
        "waypoint_threshold_m": 0.12,
        "min_move_speed": 0.05,
        "takeoff_wait_s": 5,
        "pad_land_wait_s": 1.0,
        "wait_for_search_release": True,
        "search_release_key": "e",
        "auto_release_search_in_sim": True,
        "max_mission_time_s": None,
        "move_speed": 0.35,
        "search_move_speed": 0.2,
        "hover_height_m": 0.9,
        "hover_height_max_m": 0.9,
        "hover_height_min_m": 0.85,
        "camera_pitch_enabled": True,
        "camera_pitch_mode": "DOWN_ABSOLUTE",
        "camera_pitch_angle_deg": 90,
        "obstacle_avoidance_enabled": True,
        "obstacle_source": "lidar",
        "obstacle_hard_stop_distance_m": 0.05,
        "obstacle_slowdown_rules_mps": [
            {"distance_m": 0.30, "speed_mps": 0.30},
            {"distance_m": 0.20, "speed_mps": 0.20},
            {"distance_m": 0.10, "speed_mps": 0.10},
        ],
        "obstacle_clearance_m": 0.3,
        "camera_model": "D430",
        "use_map_bounds": False,
        "search_area": {"n_min": 0.5, "n_max": 9.5, "e_min": 0.5, "e_max": 4.5},
        "search_spacing_m": 2.0,
        "detection_conf": 0.4,
        "snapshot_cooldown_s": 1.0,
        "target_dedup_m": 0.25,
        "do_area_search": True,
        "sim_camera_footprint_m": 0.35,
        "yolo_weights": "models/robomaster_best.pt",
        "snapshot_dir": "output/snapshots",
    },
}
